version: "2.24"
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80

  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: products

volumes:
  mysql-data:
